# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/home/overloard/dev/Pineapple/vendor/mariadbc;/home/overloard/dev/Pineapple/build_vendor/mariadb_build")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "ClientPlugins;SharedLibraries;ConCLib;Documentation;Development")
set(CPACK_COMPONENTS_ALL_IN_ONE_PACKAGE "1")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "mariadb_connector_cpp built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "TGZ")
set(CPACK_IGNORE_FILES "/test/;/.git/;.gitignore;.gitmodules;.gitattributes;CMakeCache.txt;cmake_dist.cmake;CPackSourceConfig.cmake;CPackConfig.cmake;/.build/;cmake_install.cmake;CTestTestfile.cmake;/CMakeFiles/;/version_resources/;.*vcxproj;.*gz$;.*zip$;.*so$;.*so.2;.*so.3;.*dll$;.*a$;.*pdb$;.*sln$;.*sdf$;install_manifest_*txt;Makefile$;tests_config.h;/autom4te.cache/;/.travis/;.travis.yml;/libmariadb/;/_CPack_Packages/")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "/home/overloard/dev/Pineapple/vendor/mariadbc;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/home/overloard/dev/Pineapple/vendor/mariadbc/cmake")
set(CPACK_NSIS_DISPLAY_NAME "mariadb-connector-cpp 1.0.7")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "mariadb-connector-cpp 1.0.7")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/overloard/dev/Pineapple/build_vendor/mariadb_build/CPackConfig.cmake")
set(CPACK_PACKAGE_API_HEADERS "/home/overloard/dev/Pineapple/vendor/mariadbc/include/")
set(CPACK_PACKAGE_CONTACT "info@mariadb.com")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "MariaDB Connector/C++. C++ driver library for connecting to MariaDB and MySQL servers")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/overloard/dev/Pineapple/vendor/mariadbc/README")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "mariadb_connector_cpp built using CMake")
set(CPACK_PACKAGE_FILE_NAME "mariadb-connector-cpp-1.0.7-src")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "mariadb-connector-cpp 1.0.7")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "mariadb-connector-cpp 1.0.7")
set(CPACK_PACKAGE_LICENSE "LGPLv2.1")
set(CPACK_PACKAGE_NAME "mariadb-connector-cpp")
set(CPACK_PACKAGE_RELEASE "1")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "MariaDB Corporation plc")
set(CPACK_PACKAGE_VERSION "1.0.7")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "7")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/overloard/dev/Pineapple/vendor/mariadbc/COPYING")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_SOURCE_IGNORE_FILES "/test/;/.git/;.gitignore;.gitmodules;.gitattributes;CMakeCache.txt;cmake_dist.cmake;CPackSourceConfig.cmake;CPackConfig.cmake;/.build/;cmake_install.cmake;CTestTestfile.cmake;/CMakeFiles/;/version_resources/;.*vcxproj;.*gz$;.*zip$;.*so$;.*so.2;.*so.3;.*dll$;.*a$;.*pdb$;.*sln$;.*sdf$;install_manifest_*txt;Makefile$;tests_config.h;/autom4te.cache/;/.travis/;.travis.yml;/libmariadb/;/_CPack_Packages/")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/overloard/dev/Pineapple/vendor/mariadbc;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/overloard/dev/Pineapple/build_vendor/mariadb_build/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "mariadb-connector-cpp-1.0.7-src")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/overloard/dev/Pineapple/build_vendor/mariadb_build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
